### PR TITLE
 Make tests using patchwork running under PHP 7.3

### PR DESCRIPTION
**Pull request by kagg-design**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6496

### CODE REVIEW

**Comment by kagg-design** [comment]
We should not merge it into master, as it is upgrade of outdated version 2.0.9.

**Comment by strategio** [comment]
@kagg-design, don't you think we should open a PR on https://github.com/antecedent/patchwork? I don't see a reason to create a fork for us.

**Comment by kagg-design** [comment]
@strategio No reason. First of all, author of patchwork does not answer for more than 1 year. I sent a PR to his repo 2 months ago - no reaction. Secondly, we need to patch outdated version 2.0.9. Current version is 2.1.9. We need outdated 2.0.9, because `wp-mock 0.2.0` and `lucatime` require `patchwork ^2.0`. Andrea proposed to write to `wp-mock`, but I also see no reason, as we use outdated 0.2.0, when current version is 0.4.0 - they simple will not react. 

Our problem is in outdated phpunit 5.7 (when current is phpunit 8), but it is the last version which supports php 5.6.

I tried to change phpunit 5.7 to phpunit 8 on my own project - tons of problems. At least setUp must be declared as `setUp(): void {` - and you can imagine number of changes.

Summarising all of these, I see no other reason as to support our own fork until WP will bump up php to 7, and we have to switch to phpunit 8.

**Review by strategio — APPROVED** [review]
Got it @kagg-design +1

**Comment by ghost** [comment]
+1 @kagg-design

**Comment by kagg-design** [comment]
This PR was created only for reviews. It should not be merged into master, as we upgrade old version 2.0.9.

So I close this PR. Our plugins use now this branch 2-0-10.

**Pull request closed without merging**
